feat: drink service and controller
Sybit-Education/Coding-Camp-2023-backend pull request #6
Opened 2023-08-02 12:12 UTC by AlexanderKugler

2023-08-02 12:31 UTC, Der-Zauberer approved these changes

2023-08-02 12:32 UTC, Der-Zauberer requested changes

2023-08-02 13:28 UTC, AlexanderKugler commented on src/main/java/de/sybit/sygotchi/tamagotchi/TamagotchiService.java
> +        tamagotchi.setThirst(tamagotchi.getThirst() +20);
Ist gefixt 👍

2023-08-03 05:04 UTC, Der-Zauberer requested changes

2023-08-03 05:04 UTC, Der-Zauberer commented on src/main/java/de/sybit/sygotchi/tamagotchi/TamagotchiService.java
> +        tamagotchi.setThirst(tamagotchi.getThirst() +20);
Where is it fixed? Its still possible to have a thirst of more than 100!

2023-08-03 08:15 UTC, JanSteppacher approved these changes

2023-08-03 08:28 UTC, merged